sources:
  - name: gz_raw_data
    tables:
      - name: raw_gz_product 
        columns : 
          - name: products_id
            description: primer_key
          - name: purchSE_PRICE
            description: product table 
      - name: raw_gz_sales 
        columns : 
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity
            description: sales table
      - name: raw_gz_ship 
        columns : 
          - name: orders_id
            description: primer_key
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost
                  
            description: ship table            
