sources:
  - name: gz_raw_data
    tables:
      - name: raw_gz_product 
        columns : 
          - name: products_id
            description: primer_key
          - name: purchSE_PRICE
            description: product table 
      - name: raw_gz_sales 
        freshness: 
          warn_after: {count: 90, period: day} 
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"  
        tests:
           - unique:
                  column_name : "(orders_id||'-'||pdt_id)"  
                          
        columns : 
           - name: date_date
           - name: revenue
           - name: orders_id
           - name: pdt_id
           - name: quantity
         
      - name: raw_gz_ship 
        columns : 
          - name: orders_id
            description: primer_key
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost
                  
            description: ship table    

      - name: raw_gz_adwords
        tests:
           - unique:
                  column_name :  "(campaign_key||'-'||date_date)"  
        columns : 
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      
      - name: raw_gz_bing 
        columns : 
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click

      - name: raw_gz_criteo
        columns : 
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click

      - name: raw_gz_facebook
        columns : 
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click


models:
  - name: int_orders_margin
    description: Orders margin details.
    columns:
      - name: orders_id
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_orders_operational
    description: Orders operational margin details.
    columns:
      - name: orders_id
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_sales_margin
    description: Sales margin details.
    columns:
      - name: orders_id
        description: Identifiant de commande.
        tests:
          - not_null

  - name: finance_days
    description: Finance days info.
    columns:
      - name: date_date
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_campaigns
    description: campaign
    columns:
      - name: "(campaign_key||'-'||date_date)" 
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_campaigns_day
    description: Campaign per days
    columns:
      - name: date_date
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: Finance_campaigns_day
    description: Campaign per days
    columns:
      - name: date_date
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: Finance_campaigns_month
    description: Campaign per days
    columns:
      - name: datemonth
        description: Primary key.
        tests:
          - unique
          - not_null





















           
