sources:
  - name: gz_raw_data
    tables:
      - name: raw_gz_product 
        columns : 
          - name: products_id
            description: primer_key
          - name: purchSE_PRICE
            description: product table 
      - name: raw_gz_sales 
        tests:
           - unique:
                  column_name : "(orders_id||'-'||pdt_id)"  
        freshness: 
          warn_after: {count: 90, period: day} 
        loaded_at_field: "CAST(cate_date AS TIMESTAMP)"  
                          
        columns : 
           - name: date_date
           - name: revenue
           - name: orders_id
           - name: pdt_id
           - name: quantity
         
      - name: raw_gz_ship 
        columns : 
          - name: orders_id
            description: primer_key
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost
                  
            description: ship table            
